# Generated by Django 5.0.14 on 2025-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_student_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="classroom",
        ),
        migrations.AddField(
            model_name="student",
            name="classroom",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="account.classroom"
            ),
        ),
    ]
