# Generated by Django 5.0.14 on 2025-12-05 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_powershellchecklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="BashChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_files", models.BooleanField(default=False)),
                ("system_info", models.BooleanField(default=False)),
                ("move_location", models.BooleanField(default=False)),
                ("read_write", models.BooleanField(default=False)),
                ("manipulate_files", models.BooleanField(default=False)),
                ("navigate", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bash_checklist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
